AUXILIAR_STATUS_CODES = {
    0x0: 'Memoria fiscal no formateada.',
    0x1: 'Memoria fiscal no inicializada.',
    0x2: 'No hay ningún comprobante abierto.',
    0x3: 'Un comprobante fiscal se encuentra abierto. Se puede vender.',
    0x4: 'Comprobante fiscal abierto. Se acaba de imprimir un texto fiscal.',
    0x5: 'Un comprobante no fiscal se encuentra abierto.',
    0x6: 'Comprobante fiscal abierto. Se realizó al menos un pago.',
    0x7: 'Comprobante fiscal abierto. Se saldó el monto.',
    0x8: 'Comprobante fiscal abierto. Se ha emitido el comando de percepciones.',
    0x9: 'El controlador ha sido dado de baja.',
    0xA: 'Comprobante fiscal abierto. Se realizó un descuento / recargo general.',
    0xB: 'Comprobante fiscal abierto. Se realizó una bonificación / recargo / devolución de envases.',
    0xC: 'Recibo fiscal abierto. Se acaba de imprimir una línea con el concepto del recibo.',
    0xD: 'Una nota de crédito o recibo de uso interno se encuentra abierto. Se puede hacer una venta (crédito o recibo).',
    0xE: 'Nota de crédito o recibo de uso interno abierto. Se realizó un descuento / recargo general.',
    0xF: 'Nota de crédito o recibo de uso interno abierto. Se realizó una bonificación / recargo / devolución de envases.',
    0x10: 'Nota de crédito o recibo de uso interno abierto. Se ha emitido el comando de percepciones.',
    0x11: 'Nota de crédito o recibo de uso interno abierto. Se acaba de escribir una línea de texto.',
    0x12: 'Recibo de uso interno abierto. Se acaba de imprimir una línea con el concepto del recibo.',
    0x13: 'Una cotización se encuentra abierta.',
    0x14: 'Un remito / orden de salida se encuentra abierto.',
    0x15: 'Un resumen de cuenta / cargo a la habitación se encuentra abierto.',
    0x16: 'Controlador fiscal bloqueado.'
}