COMANDOS_ART_BDD =[
    {
        "*":{
            "auxiliar_status":3,
            "document_status":5,
    }},{
        "@":{
            "auxiliar_status":-1,
            "document_status":-1,
    }},{
        "A":{
            "auxiliar_status":-1,
            "document_status":-1,
    }},{
        "B":{
            "auxiliar_status":-1,
            "document_status":-1,
    }},{
        "C":{
            "auxiliar_status":-1,
            "document_status":-1,
    }},{
        "D":{
            "auxiliar_status":-1,
            "document_status":-1,
    },},{
        "E":{
            "auxiliar_status":-1,
            "document_status":-1,
    }},
]
